### ISSUE TITLE
Allow buttons to work like quick replies in the Tryout screen

### ISSUE THREAD

**Issue by Geeza** [flow-ai/backlog#118]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
- bug report
- feature request 

#### What is the current behavior?
Right now buttons do not work in the tryout window

#### If the current behavior is a bug, please provide the steps to reproduce and if possible a screenshot of the problem:
- Add a flow
- Add a trigger and a card or carousel
- Add a button to the card or carousel
- Save and open tryout
- Trigger the flow and press the button

#### What is the expected behavior?
When you add a button and use it on the tryout screen it works like in messenger or the web widget

#### What is the motivation/use case for changing the behavior?
It improves speed and usefulness of the tryout screen

#### Please tell us about your environment:

- Browser: [all]
- OS: [all ]

## TODO:
This will be filled out by us (Flow.ai team). Want to collaborate? Let us know on [our Slack channel](https://slack.flow.ai)! 
- [ ] Adjust dashboard / tryout widgets (buttons, card, carousel, actions with image, video, audio)
- [ ] Add actions like with quick replies
- [ ] Test it with all the various button types

**Comment by chrisdenarend** [comment]
Hi, Cards are working fine, it's only for Carousel.
