### ISSUE TITLE
Send user token with user information

### ISSUE THREAD

**Issue by Geeza** [flow-ai/backlog#120]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
- feature request

#### What is the current behavior?
When you link accounts with Alexa you get a user token, it's not forwarded to actions/webhooks

#### What is the expected behavior?
Send the user token if received on Alexa

#### What is the motivation/use case for changing the behavior?

It's useful if you want to identify with your own system

#### Please tell us about your environment:

- Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari]
- OS: [all | Windows X.X | macOS | iOS ]

#### Other information (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context)
See the docs: 
https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html

## TODO:
This will be filled out by us (Flow.ai team). Want to colleborate? Let us know on [our Slack channel](https://slack.flow.ai)! 
- [ ] Check if user token is received
- [ ] Add it to user meta properties
- [ ] Update the documentation
