### ISSUE TITLE
Add support for email quick reply (facebook messenger)

### ISSUE THREAD

**Issue by Geeza** [flow-ai/backlog#127]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
- feature request

#### What is the current behavior?
You cannot use the email quick reply on messenger

#### What is the expected behavior?
Use the email quick reply just like you can for locations

#### What is the motivation/use case for changing the behavior?
Support messenger features

## TODO:
This will be filled out by us (Flow.ai team). Want to colleborate? Let us know on [our Slack channel](https://slack.flow.ai)! 

- [ ] Add to UI
- [ ] Support in Messenger Channel
- [ ] Think about behavior on different channels
