### ISSUE TITLE
Remove chats from the UI

### ISSUE THREAD

**Issue by Geeza** [flow-ai/backlog#128]
**Note: for support questions, please use [slack](https://slack.flow.ai)**. This repository's issues are reserved for feature requests and bug reports.

#### I'm submitting a ...
- feature request

#### What is the current behavior?
You cannot delete individual chats from the app

#### What is the expected behavior?
Allow a user signed into the dashboard to delete a chat and all it's related information

#### What is the motivation/use case for changing the behavior?
In order to comply with GDPR you must be able to delete a seperate chat with a user

#### Please tell us about your environment:
- Browser:all
- OS: all

## TODO:
- [ ] Adjust data storage service
- [ ] Update all services
- [ ] Update socket service
- [ ] Add delete button to the Chat app
